# Generated by Django 3.1.12 on 2021-08-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('item_id', models.IntegerField()),
                ('name', models.CharField(max_length=250)),
                ('is_favorite', models.BooleanField(default=False)),
                ('category', models.IntegerField(choices=[(1, 'planets'), (2, 'films'), (3, 'people'), (4, 'starships')])),
            ],
        ),
    ]
